services:
  portal-contribuinte:
    build: .
    container_name: portal-contribuinte
    restart: unless-stopped
    ports:
      - "3006:3006"
    environment:
      - VIRTUAL_HOST=contribuinte.mauriciosti.xyz
